apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-source
  namespace: prism-monitoring
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: https://prometheus-k8s-openshift-monitoring.apps.openshift.androme.da/api
      version: 1
  name: prometheus-source.yaml