apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: prism-grafana
  namespace: prism-monitoring
spec:
  config:
    auth.generic_oauth:
      auto_login: true
    auth.github:
      enabled: true
      allow_sign_up: true
      auto_login: true
      client_id: YOUR_GITHUB_APP_CLIENT_ID
      client_secret: YOUR_GITHUB_APP_CLIENT_SECRET
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: Prism-hosting
status:
  message: success
  phase: reconciling
  previousServiceName: grafana-service